# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitHooks < Formula
  desc ""
  homepage "https://github.com/lvrach/git-hooks/"
  version "0.0.1-rc2"

  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/lvrach/git-hooks/releases/download/v0.0.1-rc2/git-hooks_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "77c7f19f2ae842039a7f19fa4fbb0f990a6a0f1aa6a2bcb0f10634cd3fcf393e"

      def install
        bin.install "git-hooks"
        bash_completion.install "completions/foo.bash" => "foo"
      end
    end
    on_arm do
      url "https://github.com/lvrach/git-hooks/releases/download/v0.0.1-rc2/git-hooks_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "e1780720ebe268bd46f5107f9259c5ff6d4ca7700fe2517cf9b467d4fe802b81"

      def install
        bin.install "git-hooks"
        bash_completion.install "completions/foo.bash" => "foo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvrach/git-hooks/releases/download/v0.0.1-rc2/git-hooks_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "a7f8417c7166b40ca2e3c2655d939eb3986497bab8e79ba02add507b8334e72a"

        def install
          bin.install "git-hooks"
          bash_completion.install "completions/foo.bash" => "foo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvrach/git-hooks/releases/download/v0.0.1-rc2/git-hooks_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "c7807e11a6a9a0f3c36dc8a9f84812e3c77c54b1bee1c97f6e7f5a7b5ee5e628"

        def install
          bin.install "git-hooks"
          bash_completion.install "completions/foo.bash" => "foo"
        end
      end
    end
  end

  test do
    system "#{bin}/git-hooks"
  end
end
